export const fieldInput = {
  email: "Email",
  name: "Name",
  surname: "Surname",
  fatherName: "Fathername",
  birthday: "Birdthday",
  citizenship: "Citizenship",
  phoneNumber: "PhoneNumber",
  country: "Country",
  city: "City",
  address_1: "Address 1",
  inn: "INN",
  passport: "Passport",
};

export const fieldInputForForm = {
  email: "Email",
  name: "Name",
  surname: "Surname",
  fatherName: "Fathername",
  birthday: "Birdthday",
  citizenship: "Citizenship",
  inn: "INN",
  passport: "Passport",
  requesterFile: "Document confirming kinship",
  requesterBirthday: "Date of birth (person making the request)",
  requesterName: "Full name (person making the request)",
  couplePIB1: "Spouse's full name (husband's)",
  couplePIB2: "Spouse's full name (wife's)",
  "residence.address": "Residential Address",
  "residence.city": "City of Residence",
  "residence.country": "Country of Residence",
  deadName: "Full name of deceased",
  deadDeathDay: "Date of death",
  deadBirthday: "Date of birth of deceased",
  deadRelationship: "Relationship to deceased",
  "recipient.name": "Name (district) of the Territorial Recruitment Centers",
  "recipient.address": "Email of the Territorial Recruitment Centers",
  rank: "Rank",
  unit: "Military unit number",
  "date.start": "Start date", // В НИХ МАБТЬ БУТИ РІЗНІ НАЗВИ БО ЦЕ ДВА РІЗНІ ЗАПИТИ
  "date.end": "End date", // В НИХ МАБТЬ БУТИ РІЗНІ НАЗВИ БО ЦЕ ДВА РІЗНІ ЗАПИТИ
  abroadPassnum: "Series and number of the international passport",
  pmjNum: "Residence permit",
  coupleBirthday1: "Husband's date of birth",
  coupleBirthday2: "Wife's date of birth",
  dateResidence: "Date of issuance of residence certificate",
  placeResidence: "Place of residence",
  eventDate: "Event date",
  eventTime: "Event time",
  eventPlace: "Event location",
  propertyAddress: "Property address",
  servicemanPIB: "Full name of serviceman", //
};

export const patternInput = {
  email: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
  name: /^[a-zA-Zа-яА-ЯіІїЇ]{2,30}$/,
  surname: /^[a-zA-Zа-яА-ЯіІїЇ]{2,30}$/,
  fatherName: /^[a-zA-Zа-яА-ЯіІїЇ]{2,30}$/,
  birthday: /^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-\d{4}$/,
  citizenship: /^[a-zA-Zа-яА-ЯіІїЇ\s]{2,30}$/,
  phoneNumber: /^\d{6,14}$/,
  country: /^[a-zA-Zа-яА-ЯіІїЇ\s]{2,30}$/,
  city: /^[a-zA-Zа-яА-ЯіІїЇ\s]{2,30}$/,
  address_1: /^[\w\s,.'\-\u00C0-\u024F\u0400-\u04FF]{5,100}$/,
  inn: /^\d{6,14}$/,
  passport: /^[A-Z0-9]{6,9}$/,
  requesterFile: /.+/,
  requesterBirthday: /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/,
  requesterName: /^[a-zA-Zа-яА-ЯіІїЇ\s]{2,100}$/,
  couplePIB1: /^[a-zA-Zа-яА-ЯіІїЇ\s]{2,100}$/,
  couplePIB2: /^[a-zA-Zа-яА-ЯіІїЇ\s]{2,100}$/,
  "residence.address": /^[\w\s,.'\-\u00C0-\u024F\u0400-\u04FF]{5,100}$/,
  "residence.city": /^[a-zA-Zа-яА-ЯёЁіІїЇ\s]{2,30}$/,
  "residence.country": /^[a-zA-Zа-яА-ЯёЁіІїЇ\s]{2,30}$/,
  deadName: /^[a-zA-Zа-яА-ЯіІїЇ\s]{2,100}$/,
  deadDeathDay: /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/,
  deadBirthday: /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/,
  deadRelationship: /^[a-zA-Zа-яА-ЯіІїЇ]{2,100}$/,
  "recipient.name": /^[a-zA-Zа-яА-ЯіІїЇ]{2,100}$/,
  "recipient.address": /^[\w\s,.'\-\u00C0-\u024F\u0400-\u04FF]{5,100}$/,
  rank: /^[\w\s,.'/\\-а-яА-ЯіІїЇ0-9]{2,100}$/,
  unit: /^[\w\s,.'/\\-а-яА-ЯіІїЇ0-9]{2,100}$/,
  "date.start": /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/,
  "date.end": /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/,
  abroadPassnum: /^[A-Z0-9]{3,30}$/,
  pmjNum: /^[A-Z0-9]{3,30}$/,
  coupleBirthday1: /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/,
  coupleBirthday2: /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/,
  dateResidence: /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/,
  placeResidence: /^[\w\s,.'\-\u00C0-\u024F\u0400-\u04FF]{5,100}$/,
  eventDate: /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/,
  eventTime: /^([01]\d|2[0-3]):([0-5]\d)$/,
  eventPlace: /^[\w\s,.'\-\u00C0-\u024F\u0400-\u04FF]{5,}$/,
  propertyAddress: /^[\w\s,.'\-\u00C0-\u024F\u0400-\u04FF]{5,}$/,
  servicemanPIB: /^[a-zA-Zа-яА-ЯіІїЇ\s]{2,100}$/,
};

export const placeHolder = {
  email: "example@gmail.com",
  name: "Vasyl",
  surname: "Shevchenko",
  fatherName: "Mukolavivich",
  birthday: "03-05-1980",
  citizenship: "Ukrainian",
  phoneNumber: "06778787897",
  country: "Ukraine",
  city: "Kyiv",
  address_1: "Obolonskya str 33, 24",
  inn: "123456789",
  passport: "NC456376",
  requesterFile: "Add a file",
  requesterBirthday: "03-05-1980",
  requesterName: "Write a full name",
  couplePIB1: "Write a full name",
  couplePIB2: "Write a full name",
  "residence.address": "Obolonskya str 33, 24",
  "residence.city": "Kyiv",
  "residence.country": "Ukraine",
  deadName: "Write a full name",
  deadDeathDay: "03.05.1980",
  deadBirthday: "03.05.1980",
  deadRelationship: "Relationship to deceased",
  "recipient.name": "Житомирський ОМТЦК та СП",
  "recipient.address": "example@gmail.com",
  rank: "Rank",
  unit: "Military unit number",
  "date.start": "03.05.1980",
  "date.end": "03.05.1987",
  abroadPassnum: "NC456376",
  pmjNum: "NC456376",
  coupleBirthday1: "03.05.1985",
  coupleBirthday2: "03.05.1982",
  dateResidence: "03.05.2025",
  placeResidence: "Obolonskya str 33, 24, Kyiv",
  eventDate: "03.05.2025",
  eventTime: "16:49",
  eventPlace: "Obolonskya str 33, 24, Kyiv",
  propertyAddress: "Obolonskya str 33, 24, Kyiv",
  servicemanPIB: "Write a full name",
};

export const inputTypes = {
  email: "email",
  name: "text",
  surname: "text",
  fatherName: "text",
  birthday: "text",
  citizenship: "text",
  phoneNumber: "number",
  country: "text",
  city: "text",
  address_1: "text",
  inn: "number",
  passport: "text",
  requesterFile: "file",
  requesterBirthday: "date",
  requesterName: "text",
  couplePIB1: "text",
  couplePIB2: "text",
  "residence.address": "text",
  "residence.city": "text",
  "residence.country": "text",
  deadName: "text",
  deadDeathDay: "date",
  deadBirthday: "date",
  deadRelationship: "text",
  "recipient.name": "text",
  "recipient.address": "email",
  rank: "text",
  unit: "text",
  "date.start": "date",
  "date.end": "date",
  abroadPassnum: "text",
  pmjNum: "text",
  coupleBirthday1: "date",
  coupleBirthday2: "date",
  dateResidence: "date",
  placeResidence: "text",
  eventDate: "date",
  eventTime: "time",
  eventPlace: "text",
  propertyAddress: "text",
  servicemanPIB: "text",
};
