// 'use server';
import { db } from "../../firebase";

export default async function saveCredentials(userCredentials) {
  try {
    // Optionally use a unique ID for each document (e.g., based on user or timestamp)
    const userRef = db.collection("users").doc(); // Creates a new document with an autogenerated ID

    await userRef.set(userCredentials);

    console.log("Credentials saved successfully!");
    return 1;
  } catch (error) {
    console.error("Error saving credentials: ", error);
  }
}
